use crate::{
    runtime::Runtime,
    vm::{
        bytecode::VMWidth,
        handlers::semantic::{self, Effect, Expression, Operand, Operation},
    },
};

pub fn build(rt: &mut Runtime) {
    semantic::compiler::compile(
        rt,
        &Operation {
            effects: vec![
                Effect::Assign(Expression::BitAnd(
                    Box::new(Expression::BitShr(
                        Box::new(Expression::Operand(Operand::Input(0))),
                        Box::new(Expression::Sub(
                            Box::new(Expression::BitSize),
                            Box::new(Expression::Constant(8)),
                        )),
                    )),
                    Box::new(Expression::Constant(0xFF)),
                )),
                Effect::Or(
                    Expression::Operand(Operand::Output(0)),
                    Expression::BitAnd(
                        Box::new(Expression::BitShr(
                            Box::new(Expression::Operand(Operand::Input(0))),
                            Box::new(Expression::Sub(
                                Box::new(Expression::BitSize),
                                Box::new(Expression::Constant(24)),
                            )),
                        )),
                        Box::new(Expression::Constant(0xFF00)),
                    ),
                ),
                Effect::Or(
                    Expression::Operand(Operand::Output(0)),
                    Expression::BitAnd(
                        Box::new(Expression::BitShr(
                            Box::new(Expression::Operand(Operand::Input(0))),
                            Box::new(Expression::Sub(
                                Box::new(Expression::BitSize),
                                Box::new(Expression::Constant(40)),
                            )),
                        )),
                        Box::new(Expression::Constant(0xFF_0000)),
                    ),
                ),
                Effect::Or(
                    Expression::Operand(Operand::Output(0)),
                    Expression::BitAnd(
                        Box::new(Expression::BitShr(
                            Box::new(Expression::Operand(Operand::Input(0))),
                            Box::new(Expression::Sub(
                                Box::new(Expression::BitSize),
                                Box::new(Expression::Constant(56)),
                            )),
                        )),
                        Box::new(Expression::Constant(0xFF_000000)),
                    ),
                ),
                Effect::Or(
                    Expression::Operand(Operand::Output(0)),
                    Expression::BitAnd(
                        Box::new(Expression::BitShl(
                            Box::new(Expression::Operand(Operand::Input(0))),
                            Box::new(Expression::Sub(
                                Box::new(Expression::BitSize),
                                Box::new(Expression::Constant(56)),
                            )),
                        )),
                        Box::new(Expression::ByteMask(3)),
                    ),
                ),
                Effect::Or(
                    Expression::Operand(Operand::Output(0)),
                    Expression::BitAnd(
                        Box::new(Expression::BitShl(
                            Box::new(Expression::Operand(Operand::Input(0))),
                            Box::new(Expression::Sub(
                                Box::new(Expression::BitSize),
                                Box::new(Expression::Constant(40)),
                            )),
                        )),
                        Box::new(Expression::ByteMask(2)),
                    ),
                ),
                Effect::Or(
                    Expression::Operand(Operand::Output(0)),
                    Expression::BitAnd(
                        Box::new(Expression::BitShl(
                            Box::new(Expression::Operand(Operand::Input(0))),
                            Box::new(Expression::Sub(
                                Box::new(Expression::BitSize),
                                Box::new(Expression::Constant(24)),
                            )),
                        )),
                        Box::new(Expression::ByteMask(1)),
                    ),
                ),
                Effect::Or(
                    Expression::Operand(Operand::Output(0)),
                    Expression::BitAnd(
                        Box::new(Expression::BitShl(
                            Box::new(Expression::Operand(Operand::Input(0))),
                            Box::new(Expression::Sub(
                                Box::new(Expression::BitSize),
                                Box::new(Expression::Constant(8)),
                            )),
                        )),
                        Box::new(Expression::ByteMask(0)),
                    ),
                ),
            ],
            flags: vec![],
            stores: None,
            widths: &[VMWidth::Lower64, VMWidth::Lower32],
        },
    );
}
