[package]
name = "runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
iced-x86 = { version = "1.21.0", features = ["code_asm"] }
serde = { version = "1.0.215", features = ["derive"] }
bincode = "1.3.3"
