name: Validate Examples

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: x86_64-pc-windows-gnu

      - name: Install dependencies
        run: |
          sudo dpkg --add-architecture i386

          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://repo.charm.sh/apt/gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/charm.gpg
          echo "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *" | sudo tee /etc/apt/sources.list.d/charm.list

          sudo apt-get update
          sudo apt-get install -y mingw-w64 wine wine32 wine64

      - name: Build for Windows
        run: cargo build --bin obfuscator --release --target x86_64-pc-windows-gnu

      - name: Build example
        run: x86_64-w64-mingw32-g++ examples/cpp/hello/main.cpp -o example.exe

      - name: Obfuscate example
        run: wine target/x86_64-pc-windows-gnu/release/obfuscator.exe example.exe --virtualization

      - name: Validate example
        run: wine example.exe
